categories:
  - title: '🚀 Added'
    label: 'added'
  - title: '⬆️ Updated'
    label: 'updated'
  - title: '🐛 Fixed'
    label: 'fixed'
  - title: '🔧 Maintenance'
    label: 'maintenance'
template: |
  ## Changes

  $CHANGES
