language: node_js
sudo: false
node_js:
  - "8.11.2"

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    tags: true

cache:
  yarn: true
  directories:
    - node_modules
