name: Deploy
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    name: Deploy the extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js version from .nvmrc
      id: get-node-version
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
    - name: Get version from ref
      id: get-version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.get-node-version.outputs.NODE_VERSION }}'
    - run: npm install
    - name: Deploy the extension
      run: |
        npx grunt publish:chrome
        npx grunt publish:firefox
      env:
        AMO_ISSUER: ${{ secrets.AMO_ISSUER }}
        AMO_SECRET: ${{ secrets.AMO_SECRET }}
        CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
    - name: Publish release on GitHub
      uses: test-room-7/action-publish-release-drafts@v0
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: ${{ steps.get-version.outputs.VERSION }}
    - name: Request website update
      run: |
        curl -X POST \
            -H "Authorization: token ${GH_FA_TOKEN}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d "{\"event_type\":\"${VERSION}\"}" \
            https://api.github.com/repos/${WEBSITE_REPO}/dispatches
      env:
        GH_FA_TOKEN: ${{ secrets.GH_FA_TOKEN }}
        WEBSITE_REPO: web-scrobbler/website-resources
        VERSION: ${{ steps.get-version.outputs.VERSION }}
