name: deploy
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Deploy the extension
      run: |
        yarn run grunt publish:chrome
        yarn run grunt publish:firefox
        yarn run grunt github_release
      env:
        AMO_ISSUER: ${{ secrets.AMO_ISSUER }}
        AMO_SECRET: ${{ secrets.AMO_SECRET }}
        CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
