name: Label pull requests
on: [pull_request]
jobs:
  triage:
    name: Add labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
