name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Run linters
      run: |
        yarn run lint
      env:
        CI: true 
    - name: Run tests
      if: github.ref != 'refs/heads/master'
      run: |
        yarn run test
    - name: Run tests with coverage
      if: github.ref == 'refs/heads/master'
      run: |
        yarn run test-with-coverage
        yarn run upload-coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
